openapi: 3.0.3
info:
  title: plugin-list API
  description: plugin-list API
  version: 1.0.0

paths:
  /servers/:
    get:
      summary: Get the list of servers
      description: Get the list of servers
      operationId: getServerNames
      responses:
        '200':
          description: the list of servers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["test_1", "test_2"]
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /servers/{server_name}/plugins:
    get:
      summary: Get the list of installed plugins
      description: Get the list of plugins that are installed in the specified server
      operationId: getPluginsByServer
      parameters:
        - name: server_name
          in: path
          description: the server name to get plugins
          required: true
          schema:
            type: string
      responses:
        '200':
          description: the list of plugins that are installed in the specified server
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plugin'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add or update the plugins
      description: Add or update the plugins
      operationId: addPlugins
      security:
        - Token: [ ]
      parameters:
        - name: server_name
          in: path
          description: the server name to get plugins
          required: true
          schema:
            type: string
      requestBody:
        description: Plugins to add to the list
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  plugin_name:
                    type: string
                    description: Name of the plugin
                  file_name:
                    type: string
                    description: File name of the plugin
                  version:
                    type: string
                    description: Version of the plugin
                  type:
                    type: string
                    description: Type of the plugin
                    example: "bukkit_plugin"
                  last_updated:
                    type: integer
                    format: int64
                    description: Unix time when the plugin was last updated
      responses:
        '201':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /servers/{server_name}/plugins/{plugin_name}:
    post:
      summary: Add or update the plugin
      description: Add or update the plugin
      operationId: addPlugin
      security:
        - Token: [ ]
      parameters:
        - name: server_name
          in: path
          description: the server name to get plugins
          required: true
          schema:
            type: string
        - name: plugin_name
          in: path
          description: the plugin name to get information of the plugin
          required: true
          schema:
            type: string
      requestBody:
        description: A new plugin data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                  description: File name of the plugin
                version:
                  type: string
                  description: Version of the plugin
                type:
                  type: string
                  description: Type of the plugin
                  example: "bukkit_plugin"
                last_updated:
                  type: integer
                  format: int64
                  description: Unix time when the plugin was last updated
      responses:
        '201':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete the specified plugin from the list
      description: Delete the specified plugin from the list
      operationId: deletePlugin
      security:
        - Token: [ ]
      parameters:
        - name: server_name
          in: path
          description: the server name to get information of the plugin
          required: true
          schema:
            type: string
        - name: plugin_name
          in: path
          description: the plugin name to get information of the plugin
          required: true
          schema:
            type: string
      responses:
        '204':
          description: plugin deleted
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Plugin:
      allOf:
        - properties:
            plugin_name:
              type: string
              description: Name of the plugin
            server_name:
              type: string
              description: Name of the server
            file_name:
              type: string
              description: File name of the plugin
            version:
              type: string
              description: Version of the plugin
            type:
              type: string
              description: Type of the plugin
              example: "bukkit_plugin"
            last_updated:
              type: integer
              format: int64
              description: Unix time when the plugin was last updated
          required:
            - plugin_name
            - server_name
            - file_name
            - version
            - type
            - last_updated
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: X-API-KEY
      description: A token to create/edit/delete plugins via API
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
