name: Backend CI
on:
  push:
    paths: [ 'backend/**' ]
  pull_request:
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: "Set up Go"
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: |
            backend/go.sum
      - name: "Run test"
        run: |
          cd backend
          go test -v ./...
