name: Backend CI
on:
  push:
    paths: [ 'backend/**' ]
  pull_request:
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: "Set up Go"
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: |
            backend/go.sum
      - name: "Run test"
        run: |
          cd backend
          go test -v ./...
