name: Backend CI
on:
  push:
    paths: [ 'backend/**' ]
  pull_request:
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: "Set up Go"
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.22.2"
          cache: true
      - name: "Run test"
        run: |
          cd backend
          go test -v ./...
