name: Backend CI
on:
  push:
    paths: [ 'backend/**' ]
  pull_request:
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Set up Go"
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: |
            backend/go.sum
      - name: "Run test"
        run: |
          cd backend
          go test -v ./...
