name: Frontend CI
on:
  push:
    paths: [ 'frontend/**' ]
  pull_request:
    paths: [ 'frontend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: corepack enable
      - name: "Set up Node.js"
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'
      - name: "Build"
        run: |
          cd frontend
          yarn install
          yarn run build
