name: Frontend CI
on:
  push:
    paths: [ 'frontend/**' ]
  pull_request:
    paths: [ 'frontend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: corepack enable
      - name: "Set up Node.js"
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'
      - name: "Build"
        run: |
          cd frontend
          yarn install
          yarn run build
